# Generated by Django 4.2 on 2023-05-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0010_alter_produkitem_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkitem',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produkitem',
            name='stock',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
