# Generated by Django 4.2 on 2023-05-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0011_produkitem_is_available_produkitem_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkitem',
            name='kategori',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sport wear'), ('OW', 'Outwear'), ('A', 'Accesories'), ('D', 'Dress')], max_length=2),
        ),
    ]
