# Generated by Django 4.2 on 2023-05-30 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0013_kontak'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kontak',
        ),
    ]
