# Generated by Django 4.2 on 2023-06-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0015_alter_produkitem_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkitem',
            name='stock',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
